
services:
  mesh_api:
    container_name: mesh_api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.znjofdkwekdomssjnjuu
      - SPRING_DATASOURCE_PASSWORD=vYa7IbhoTFo9VTn0
    command: java -jar todo.jar

